### ISSUE TITLE
Can you please Share sample Angular 4 project with a simple http request?

### ISSUE THREAD

**Issue by pardeep-cd** [serhiisol/ng4-http#1]
I was trying to Integrate ng4-http package.I want to add refresh auth token 401 status when Request fails 
"TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.subscribeToResult (http://localhost:4200/vendor.bundle.js:19220:27)
    at SwitchMapSubscriber._innerSub (http://localhost:4200/vendor.bundle.js:140388:63)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.bundle.js:140381:14)
    at SwitchMapSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:18930:18)
    at ScalarObservable._subscribe (http://localhost:4200/vendor.bundle.js:68958:24)
    at ScalarObservable.Observable._trySubscribe (http://localhost:4200/vendor.bundle.js:62:25)
    at ScalarObservable.Observable.subscribe (http://localhost:4200/vendor.bundle.js:50:27)
    at SwitchMapOperator.call (http://localhost:4200/vendor.bundle.js:140354:23)
    at Observable.subscribe (http://localhost:4200/vendor.bundle.js:47:22)
    at MapOperator.call (http://localhost:4200/vendor.bundle.js:64797:23)"

**Comment by pardeep-cd** [comment]
"TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.subscribeToResult (http://localhost:4200/vendor.bundle.js:19220:27)
    at SwitchMapSubscriber._innerSub (http://localhost:4200/vendor.bundle.js:140388:63)
    at SwitchMapSubscriber._next (http://localhost:4200/vendor.bundle.js:140381:14)
    at SwitchMapSubscriber.Subscriber.next (http://localhost:4200/vendor.bundle.js:18930:18)
    at ScalarObservable._subscribe (http://localhost:4200/vendor.bundle.js:68958:24)
    at ScalarObservable.Observable._trySubscribe (http://localhost:4200/vendor.bundle.js:62:25)
    at ScalarObservable.Observable.subscribe (http://localhost:4200/vendor.bundle.js:50:27)
    at SwitchMapOperator.call (http://localhost:4200/vendor.bundle.js:140354:23)
    at Observable.subscribe (http://localhost:4200/vendor.bundle.js:47:22)
    at MapOperator.call (http://localhost:4200/vendor.bundle.js:64797:23)"

**Comment by serhiisol** [comment]
Hi @pardeep-cd Sorry for answering only right now, but yes, sure I'll make plunker with examples shortly.

**Comment by serhiisol** [comment]
@pardeep-cd here's the example https://github.com/serhiisol/ng4-http-auth , I'll add more description in README of the repo tomorrow.

**Comment by ctung** [comment]
Sorry if I'm doing something wrong, I'm new to ng.
I did npm install and npm start.
When I browse to localhost:4200, I see the login button.  
However when I click it, it redirects to localhost:3000 which returns a 404.
src/app/shared/authentication/authentication.service.ts login() function POSTs to localhost:3000, but the server is running on port 4200?  Am I doing something wrong?

public login(): Observable<any> {
    return this.http.post(`http://localhost:3000/login`, { })
    .map(res => res.json())
    .do((tokens) => this.saveAccessData(tokens));
  }

**Comment by serhiisol** [comment]
You have to compile and start local server. Run ```npm run compile``` and then ```node server```.
It should start server on `localhost:3000`
